#!/bin/bash - 

#script to run a sweep of network types

#Generate sweep networks
python generateparamsweep.py

#Get network config list
netfolder=networks
nets=( $netfolder/* )

#Train networks
for net in "${nets[@]}"
do
	echo "Begining Training for $net"
	python train.py -f $net
	echo "Training Complete for $net"
	sleep 10
done

#Test networks
for net in "${nets[@]}"
do
	echo "Begining Testing for $net"
	python test.py -f $net
	echo "Testing Complete for $net"
	sleep 10
done
